### PR TITLE
Sync with https://github.com/bazelbuild/bazel-buildfarm/tree/master

### PR DESCRIPTION
**Pull request by asherf**
This PR just brings changes from the upstream repo to our fork.

context: https://toolchainlabs.slack.com/archives/CTA511NAU/p1580336673000900

### CODE REVIEW

**Review by benjyw — APPROVED** [review]
LGTM but there may be reasons I don't know about that require an older revision of this. So I'd recommend waiting for @jsirois to weigh in if possible.

Worst case, if you have to merge this to make progress, we can always revert it later if we need to, and figure something else out.

**Comment by asherf** [comment]
@benjyw no rush merging this, I am able to make progress by pointing the scripts (locally) at my fork.

**Comment by asherf** [comment]
@jsirois thoughts ?

**Review by jsirois — APPROVED** [review]

**Comment by jsirois** [comment]
LGTM! I'll look at the cherry pick PR when you rebase it against this.

**Pull request merged**
